- name: Network Getting Started First Playbook
  hosts: all
  tasks:
    - name: apt-get update
      become: true
      ansible.builtin.apt:
        update_cache: yes
    - name: Install vim
      become: true
      ansible.builtin.apt:
        name: vim
        state: latest